// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/namespaces": {
            "get": {
                "description": "获取所有命名空间列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间管理"
                ],
                "summary": "获取命名空间列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.NamespaceListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新命名空间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间管理"
                ],
                "summary": "创建命名空间",
                "parameters": [
                    {
                        "description": "命名空间信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateNamespaceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateIDResponse"
                        }
                    }
                }
            }
        },
        "/api/namespaces/:id": {
            "put": {
                "description": "更新命名空间信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间管理"
                ],
                "summary": "更新命名空间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "命名空间信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.UpdateNamespaceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定命名空间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "命名空间管理"
                ],
                "summary": "删除命名空间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            }
        },
        "/api/namespaces/:namespace_id/prompts": {
            "get": {
                "description": "获取指定命名空间和名称下的提示词列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "获取提示词列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提示词名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.PromptListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "在指定命名空间下创建新提示词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "创建提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "提示词信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.CreatePromptDraftReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateIDResponse"
                        }
                    }
                }
            }
        },
        "/api/namespaces/:namespace_id/prompts/:prompt_id": {
            "get": {
                "description": "根据ID获取提示词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "获取提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提示词ID",
                        "name": "prompt_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.PromptResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新提示词信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "更新提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提示词ID",
                        "name": "prompt_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "提示词信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.UpdatePromptDraftReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定提示词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "删除提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提示词ID",
                        "name": "prompt_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            }
        },
        "/api/namespaces/:namespace_id/prompts/:prompt_id/publish": {
            "post": {
                "description": "发布指定提示词",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "提示词管理"
                ],
                "summary": "发布提示词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间ID",
                        "name": "namespace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "提示词ID",
                        "name": "prompt_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发布成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "description": "根据分组获取配置列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取配置列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置分组",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.SettingListResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.UpdateSettingReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "创建配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateSettingReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.DeleteSettingReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            }
        },
        "/api/settings/get": {
            "post": {
                "description": "获取指定配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置管理"
                ],
                "summary": "获取配置",
                "parameters": [
                    {
                        "description": "配置查询信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.GetSettingReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.SettingResponse"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "获取所有用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.UserListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.CreateIDResponse"
                        }
                    }
                }
            }
        },
        "/api/users/:id": {
            "put": {
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/appdto.UpdateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/appdto.EmptyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "appdto.CreateIDResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.CreateNamespaceReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "appdto.CreatePromptDraftReq": {
            "type": "object",
            "required": [
                "content",
                "name"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "namespaceID": {
                    "type": "string"
                }
            }
        },
        "appdto.CreateSettingReq": {
            "type": "object",
            "required": [
                "group",
                "key",
                "value"
            ],
            "properties": {
                "group": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "key": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "appdto.CreateUserReq": {
            "type": "object",
            "required": [
                "password",
                "role",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "role": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "appdto.DeleteSettingReq": {
            "type": "object",
            "required": [
                "group",
                "key"
            ],
            "properties": {
                "group": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "key": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                }
            }
        },
        "appdto.EmptyResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.GetSettingReq": {
            "type": "object",
            "required": [
                "group",
                "key"
            ],
            "properties": {
                "group": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "key": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                }
            }
        },
        "appdto.Namespace": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "appdto.NamespaceListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appdto.Namespace"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.Prompt": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "appdto.PromptListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appdto.Prompt"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.PromptResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/appdto.Prompt"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.Setting": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "appdto.SettingListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appdto.Setting"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.SettingResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/appdto.Setting"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "appdto.UpdateNamespaceReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "appdto.UpdatePromptDraftReq": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "appdto.UpdateSettingReq": {
            "type": "object",
            "required": [
                "group",
                "key",
                "value"
            ],
            "properties": {
                "group": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "key": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "appdto.UpdateUserReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "role": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "username": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "appdto.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "appdto.UserListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/appdto.User"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Prompt Hub API",
	Description:      "Prompt Hub API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
