// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/xichan96/prompt-hub/internal/app/namespace"
	"github.com/xichan96/prompt-hub/internal/app/prompt"
	"github.com/xichan96/prompt-hub/internal/app/setting"
	"github.com/xichan96/prompt-hub/internal/app/user"
	"github.com/xichan96/prompt-hub/internal/infra/persist"
)

// Injectors from wire.go:

func NewPromptApp() prompt.AppIer {
	promptPersistIer := persist.NewPromptPersist()
	appIer := prompt.NewApp(promptPersistIer)
	return appIer
}

func NewUserApp() user.AppIer {
	userPersistIer := persist.NewUserPersist()
	appIer := user.NewApp(userPersistIer)
	return appIer
}

func NewNamespaceApp() namespace.AppIer {
	namespacePersistIer := persist.NewNamespacePersist()
	appIer := namespace.NewApp(namespacePersistIer)
	return appIer
}

func NewSettingApp() setting.AppIer {
	settingPersistIer := persist.NewSettingPersist()
	appIer := setting.NewApp(settingPersistIer)
	return appIer
}

// wire.go:

var PromptApp = NewPromptApp()

var UserApp = NewUserApp()

var NamespaceApp = NewNamespaceApp()

var SettingApp = NewSettingApp()
