// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/xichan96/prompt-hub/internal/app/agent"
	"github.com/xichan96/prompt-hub/internal/app/prompt"
	"github.com/xichan96/prompt-hub/internal/app/setting"
	"github.com/xichan96/prompt-hub/internal/app/skill"
	"github.com/xichan96/prompt-hub/internal/app/skillfile"
	"github.com/xichan96/prompt-hub/internal/app/user"
	"github.com/xichan96/prompt-hub/internal/infra/persist"
)

// Injectors from wire.go:

func NewPromptApp() prompt.AppIer {
	promptPersistIer := persist.NewPromptPersist()
	appIer := prompt.NewApp(promptPersistIer)
	return appIer
}

func NewUserApp() user.AppIer {
	userPersistIer := persist.NewUserPersist()
	appIer := user.NewApp(userPersistIer)
	return appIer
}

func NewSkillApp() skill.AppIer {
	skillPersistIer := persist.NewSkillPersist()
	promptPersistIer := persist.NewPromptPersist()
	skillFilePersistIer := persist.NewSkillFilePersist()
	appIer := skill.NewApp(skillPersistIer, promptPersistIer, skillFilePersistIer)
	return appIer
}

func NewSkillFileApp() skillfile.AppIer {
	skillFilePersistIer := persist.NewSkillFilePersist()
	appIer := skillfile.NewApp(skillFilePersistIer)
	return appIer
}

func NewSettingApp() setting.AppIer {
	settingPersistIer := persist.NewSettingPersist()
	appIer := setting.NewApp(settingPersistIer)
	return appIer
}

func NewAgentApp() agent.AppIer {
	settingPersistIer := persist.NewSettingPersist()
	appIer := setting.NewApp(settingPersistIer)
	agentAppIer := agent.NewApp(appIer)
	return agentAppIer
}

// wire.go:

var PromptApp = NewPromptApp()

var UserApp = NewUserApp()

var SkillApp = NewSkillApp()

var SkillFileApp = NewSkillFileApp()

var SettingApp = NewSettingApp()

var AgentApp = NewAgentApp()
